FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y sudo
RUN apt-get install -y zip
RUN apt-get install -y nano
RUN apt-get install -y wget
RUN apt-get install -y xz-utils
RUN apt-get install -y bash-completion
RUN apt-get install -y git

{{ ros_install }}

{{ default }}

{{ entrypoint_setup }}
