FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    zip \
    nano \
    vim \
    wget \
    xz-utils \
    bash-completion \
    git \

{{ ros_install }}

{{ default }}

RUN rm -rf /var/lib/apt/lists/*

{{ entrypoint_setup }}
