FROM quay.io/toolbx/ubuntu-toolbox:24.04

RUN apt-get update && apt-get install -y \
    apt-utils \
	bash-completion \
	bc \
	bzip2 \
	curl \
	dialog \
	diffutils \
	findutils \
	gnupg \
	gnupg2 \
	gpgsm \
	hostname \
	iproute2 \
	iputils-ping \
	keyutils \
	language-pack-en \
	less \
	libcap2-bin \
	libkrb5-3 \
	libnss-mdns \
	libnss-myhostname \
	libvte-2.9*-common \
	libvte-common \
	locales \
	lsof \
	man-db \
	manpages \
	mtr \
	ncurses-base \
	openssh-client \
	passwd \
	pigz \
	pinentry-curses \
	procps \
	rsync \
	sudo \
	tcpdump \
	time \
	traceroute \
	tree \
	tzdata \
	unzip \
	util-linux \
	wget \
	xauth \
	xz-utils \
	zip \
	nano \
	vim

{{ ros_install }}


{{ entrypoint_setup }}
