RUN apt-get update
RUN apt-get install -y ros-${ROS_DISTRO}-ros-gz
RUN apt-get install -y ros-${ROS_DISTRO}-ros2-control ros-${ROS_DISTRO}-ros2-controllers
RUN apt-get install -y ros-${ROS_DISTRO}-gz-ros2-control
