RUN apt-get update
RUN apt-get install -y ros-${ROS_DISTRO}-navigation2 ros-${ROS_DISTRO}-nav2-bringup
RUN apt-get install -y ros-${ROS_DISTRO}-slam-toolbox
RUN apt-get install -y ros-${ROS_DISTRO}-teleop-twist-joy
