RUN echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER ubuntu
RUN mkdir /home/ubuntu/ros_ws
VOLUME [ "/home/ubuntu/ros_ws" ]
WORKDIR /home/ubuntu/ros_ws

RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/ubuntu/.bashrc

ENTRYPOINT ["bash"]
