COPY ./entrypoints_templates/ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

RUN apt-get update && apt-get install -y sudo && \
    useradd -m -s /bin/bash ros && \
    echo "ros ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ros
RUN mkdir /home/ros/ros_ws
VOLUME [ "/home/ros/ros_ws" ]
WORKDIR /home/ros/ros_ws

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]