name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Specify the Python version you need

      - name: Install Python CLI tool
        run: pip install .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push desktop image
        run: |
          rosbox build desktop
          docker tag rosbox-desktop sterren642/rosbox:desktop-${{ github.ref_name }}
          docker tag rosbox-desktop sterren642/rosbox:desktop-latest
          docker push sterren642/rosbox:desktop-${{ github.ref_name }}
          docker push sterren642/rosbox:desktop-latest

      - name: Cleanup old images
              run: |
                # List all tags and sort by creation date
                tags=$(curl -s -H "Authorization: Bearer ${{ secrets.DOCKER_PASSWORD }}" "https://hub.docker.com/v2/repositories/sterren642/rosbox/tags/?page_size=100" | jq -r '.results[].name' | grep -E '^desktop-' | grep -v 'desktop-latest')
                # Keep only the latest two tags
                tags_to_keep=$(echo "$tags" | head -n 2)
                # Delete the rest
                for tag in $tags; do
                  if ! echo "$tags_to_keep" | grep -qx "$tag"; then
                    curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.DOCKER_PASSWORD }}" "https://hub.docker.com/v2/repositories/sterren642/rosbox/tags/$tag/"
                  fi
                done
